AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFront distribution with custom domain'

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket
  OriginAccessIdentityId:
    Type: String
    Description: CloudFront OAI ID
  DomainName:
    Type: String
    Description: Custom domain name
  SubdomainName:
    Type: String
    Description: Subdomain name (www.domain.com)
  CertificateArn:
    Type: String
    Description: ACM Certificate ARN

Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub 'CloudFront distribution for ${DomainName}'
        DefaultRootObject: index.html
        
        # Custom domain configuration
        Aliases:
          - !Ref DomainName
          - !Ref SubdomainName
        
        Origins:
          - Id: S3Origin
            DomainName: !Sub '${BucketName}.s3.amazonaws.com'
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${OriginAccessIdentityId}'
        
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          MinTTL: 0
          DefaultTTL: 86400
          MaxTTL: 31536000
          Compress: true
        
        # Different cache behaviors for different file types
        CacheBehaviors:
          - PathPattern: '*.html'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD]
            CachedMethods: [GET, HEAD]
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            MinTTL: 0
            DefaultTTL: 3600
            MaxTTL: 86400
            Compress: true
        
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: '/error.html'
            ErrorCachingMinTTL: 300
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: '/error.html'
            ErrorCachingMinTTL: 300
        
        PriceClass: PriceClass_100
        HttpVersion: http2
        IPV6Enabled: true
        
        # Custom SSL certificate
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

Outputs:
  DistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub '${AWS::StackName}-DistributionId'
  
  DistributionDomainName:
    Description: CloudFront Distribution Domain Name
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-DomainName'
  
  WebsiteURL:
    Description: Website URL with custom domain
    Value: !Sub 'https://${DomainName}'