AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFront distribution with WAF protection'

Parameters:
  BucketName:
    Type: String
  OriginAccessIdentityId:
    Type: String
  DomainName:
    Type: String
  SubdomainName:
    Type: String
  CertificateArn:
    Type: String
  WebACLArn:
    Type: String
    Description: WAF Web ACL ARN

Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub 'CloudFront distribution for ${DomainName} with WAF protection'
        DefaultRootObject: index.html
        
        # Associate with WAF Web ACL
        WebACLId: !Ref WebACLArn
        
        Aliases:
          - !Ref DomainName
          - !Ref SubdomainName
        
        Origins:
          - Id: S3Origin
            DomainName: !Sub '${BucketName}.s3.amazonaws.com'
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${OriginAccessIdentityId}'
        
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          MinTTL: 0
          DefaultTTL: 86400
          MaxTTL: 31536000
          Compress: true
        
        CacheBehaviors:
          - PathPattern: '*.css'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD]
            CachedMethods: [GET, HEAD]
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            MinTTL: 0
            DefaultTTL: 31536000
            MaxTTL: 31536000
            Compress: true
          - PathPattern: '*.js'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD]
            CachedMethods: [GET, HEAD]
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            MinTTL: 0
            DefaultTTL: 31536000
            MaxTTL: 31536000
            Compress: true
          - PathPattern: '*.html'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD]
            CachedMethods: [GET, HEAD]
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            MinTTL: 0
            DefaultTTL: 3600
            MaxTTL: 86400
            Compress: true
        
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: '/error.html'
            ErrorCachingMinTTL: 300
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: '/error.html'
            ErrorCachingMinTTL: 300
        
        PriceClass: PriceClass_100
        HttpVersion: http2
        IPV6Enabled: true
        
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

Outputs:
  DistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref CloudFrontDistribution
  DistributionDomainName:
    Description: CloudFront Distribution Domain Name
    Value: !GetAtt CloudFrontDistribution.DomainName
  WebsiteURL:
    Description: Website URL with WAF protection
    Value: !Sub 'https://${DomainName}'